export const REQUEST_LOAD_CURRENCIES = 'currencies/REQUEST_LOAD_CURRENCIES';
export const REQUEST_CURRENCIES_LOADING = 'currencies/REQUEST_CURRENCIES_LOADING';
export const LOAD_CURRENCIES_SUCCESSES = 'currencies/LOAD_CURRENCIES_SUCCESSES';
export const LOAD_CURRENCIES_FAILED = 'currencies/LOAD_CURRENCIES_FAILED';

export const SET_SELECTED_CURRENCY = 'currencies/SET_SELECTED_CURRENCY';
export const REMOVE_SELECTED_CURRENCY = 'currencies/REMOVE_SELECTED_CURRENCY';

export const REQUEST_LOAD_RATES = 'currencies/REQUEST_LOAD_RATES';
export const REQUEST_RATES_LOADING = 'currencies/REQUEST_RATES_LOADING';
export const LOAD_RATES_SUCCESSES = 'currencies/LOAD_RATES_SUCCESSES';
export const LOAD_RATES_FAILED = 'currencies/LOAD_RATES_FAILED';